### ISSUE TITLE
clio host host.clio fails

### ISSUE THREAD

**Issue by skrapi** [clio-lang/clio-todo#2]
I tried to run this on my local machine using the instructions in the README, I have Node, Rethinkdb and Clio installed, but I get this error:
``` bash
cliopkg.toml not found. Is it missing, or are you running tests?
(node:19788) UnhandledPromiseRejectionWarning: ReferenceError: __basedir is not defined
    at Object.clio_require (/usr/lib/node_modules/clio-lang/internals/import.js:178:31)
    at module.exports (/home/sylvan/Documents/clio-todo/.clio-cache/host.clio.js:3:20)
    at clioImport (/usr/lib/node_modules/clio-lang/internals/import.js:387:33)
    at host (/usr/lib/node_modules/clio-lang/cli/commands/host.js:20:21)
    at Object.exports.handler (/usr/lib/node_modules/clio-lang/cli/commands/host.js:11:3)
    at Object.runCommand (/usr/lib/node_modules/clio-lang/node_modules/yargs/lib/command.js:240:40)
    at Object.parseArgs [as _parseArgs] (/usr/lib/node_modules/clio-lang/node_modules/yargs/yargs.js:1095:41)
    at Object.get [as argv] (/usr/lib/node_modules/clio-lang/node_modules/yargs/yargs.js:1029:21)
    at Object.<anonymous> (/usr/lib/node_modules/clio-lang/cli/index.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
(node:19788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:19788) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by pouya-eghbali** [comment]
Hi @skrapi 

We're currently rewriting our compiler and also our tooling and utilities. Because of that we have a lot of bugs right now, but we're tying our best to do a stable release soon. 

You'll be able to run this repo if you install an older version of Clio. Once the new compiler is stable I will update the examples and documentations. 

We have a chat on telegram, you can get more details about the new Clio there: https://t.me/joinchat/B0kZo0kVldfXldTDqz95XA

**Comment by pjkasper** [comment]
OK had the same xperience was just curious getting a REPL working..trying on windows via npm.. sad
Anyone who can gimme directions on what to tell npm?

Cheers

K

**Comment by garritfra** [comment]
Unfortunately we don't have a working REPL yet, although we are planning to integrate one in the near future.  If you want to, we can discuss this in our telegram group. The current version of Clio also adds breaking changes. We haven't fixed this todo example yet. We're switching up a lot of things right now, but Clio will have a stable release soon.
